---

services:
  gts:
    image: fabianoflorentino/gts:v0.0.1
    container_name: gts
    build:
      context: .
      dockerfile: build/Dockerfile.dev
    volumes:
      - .:/app
    networks:
      - gts
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep 'sleep' || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3

networks:
  gts:
    name: gts
    driver: bridge
