---
services:
  db:
    image: postgres:17-alpine3.22
    container_name: gtsdb
    hostname: gtsdb
    env_file: ./.env
    restart: unless-stopped
    ports:
      - ${POSTGRES_LOCAL_PORT:-35432}:5432
    networks:
      - gts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gts"]
      interval: 30s
      timeout: 30s
      retries: 3
    tty: true
    stdin_open: true
  gts:
    image: fabianoflorentino/gts:v0.0.1
    container_name: gts
    hostname: gts
    env_file: ./.env
    build:
      context: .
      dockerfile: build/Dockerfile
      target: development
    volumes:
      - .:/gotostudy
    ports:
      - ${GTS_LOCAL_PORT:-8080}:8080
    networks:
      - gts
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep 'air' || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    depends_on:
      db:
        condition: service_started

networks:
  gts:
    name: gts
    driver: bridge
